"""adding a column to announcements table

Revision ID: 32f8f1a35085
Revises: 0f0b705a56c0
Create Date: 2024-07-11 21:21:15.712255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f8f1a35085'
down_revision = '0f0b705a56c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_announcement_club_id_club'), 'club', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_club_id_club'), type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
