"""Deletin a column

Revision ID: dea2ce923034
Revises: 32f8f1a35085
Create Date: 2024-07-11 23:15:23.756427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea2ce923034'
down_revision = '32f8f1a35085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_announcement_club_id_club', type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_announcement_club_id_club', 'club', ['club_id'], ['id'])

    # ### end Alembic commands ###
